"""Regenerates src/convert/pdfFonts.generated.ts.

pdfmake's bundled Roboto has no arrows, check marks, box-drawing or emoji
glyphs, so they render as empty boxes. This builds two small fallback fonts
holding only what Roboto lacks:

  * Symbols - arrows, math, box drawing, dingbats... cut from DejaVu Sans
  * Emoji   - monochrome Noto Emoji (SIL OFL 1.1)

plus a coverage table so the extension can tell the user about characters
that no bundled font can draw (e.g. CJK). Licences: THIRD_PARTY_NOTICES.md.

Run from the extension folder:
  uv run --with fonttools --with matplotlib --with brotli python scripts/make-pdf-fonts.py
"""
import base64
import io
import json
import pathlib
import subprocess
import sys
import tarfile
import tempfile

import matplotlib
from fontTools import subset
from fontTools.ttLib import TTFont

root = pathlib.Path(__file__).resolve().parent.parent
tmp = pathlib.Path(tempfile.mkdtemp())

# ---- source fonts ----------------------------------------------------------
dejavu = pathlib.Path(matplotlib.get_data_path()) / "fonts" / "ttf" / "DejaVuSans.ttf"

npm = "npm.cmd" if sys.platform == "win32" else "npm"
subprocess.run([npm, "pack", "@expo-google-fonts/noto-emoji", "--silent"], cwd=tmp, check=True)
with tarfile.open(next(tmp.glob("*.tgz"))) as tar:
    member = tar.getmember("package/400Regular/NotoEmoji_400Regular.ttf")
    tar.extract(member, tmp)
noto = tmp / "package/400Regular/NotoEmoji_400Regular.ttf"

subprocess.run(
    [
        "node",
        "-e",
        "const f=require(%s);const v=f.pdfMake?f.pdfMake.vfs:f;"
        "require('fs').writeFileSync(%s,Buffer.from(v['Roboto-Regular.ttf'],'base64'));"
        % (
            json.dumps(str(root / "node_modules/pdfmake/build/vfs_fonts")),
            json.dumps(str(tmp / "roboto.ttf")),
        ),
    ],
    check=True,
)
roboto = set(TTFont(tmp / "roboto.ttf").getBestCmap())
dv = set(TTFont(dejavu).getBestCmap())
nt = set(TTFont(noto).getBestCmap())

# ---- which code points go to which fallback -------------------------------
SYMBOL_BLOCKS = [
    (0x2190, 0x21FF),  # arrows
    (0x2200, 0x22FF),  # math operators
    (0x2300, 0x23FF),  # misc technical
    (0x2500, 0x259F),  # box drawing + blocks
    (0x25A0, 0x25FF),  # geometric shapes
    (0x2600, 0x26FF),  # misc symbols
    (0x2700, 0x27BF),  # dingbats (check marks, crosses)
    (0x27F0, 0x27FF),  # supplemental arrows A
    (0x2900, 0x297F),  # supplemental arrows B
]
symbols = sorted(
    cp for lo, hi in SYMBOL_BLOCKS for cp in range(lo, hi + 1) if cp in dv and cp not in roboto
)
symbol_set = set(symbols)

# Emoji: anything in Noto Emoji that neither Roboto nor the symbol font has,
# skipping ASCII (keycap digits) and joiners/selectors, which we strip in code.
SKIP = {0x200D, 0x20E3, 0xFE0E, 0xFE0F} | set(range(0x1F3FB, 0x1F400)) | set(range(0, 0x80))
emoji = sorted(cp for cp in nt if cp not in roboto and cp not in symbol_set and cp not in SKIP)


def make_subset(src: pathlib.Path, unicodes: list[int], family: str) -> bytes:
    opts = subset.Options()
    opts.layout_features = []
    opts.name_IDs = [1, 2, 3, 4, 6]
    opts.notdef_outline = True
    opts.hinting = False
    opts.desubroutinize = True
    font = TTFont(src)
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=unicodes)
    sub.subset(font)
    # The DejaVu licence requires modified fonts to drop the original name.
    for rec in font["name"].names:
        if rec.nameID in (1, 4, 16):
            rec.string = family
        elif rec.nameID == 6:
            rec.string = family.replace(" ", "")
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def ranges_of(cps: list[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = prev = None
    for cp in sorted(cps):
        if start is None:
            start = prev = cp
        elif cp == prev + 1:
            prev = cp
        else:
            out.append((start, prev))
            start = prev = cp
    if start is not None:
        out.append((start, prev))
    return out


def js_class(cps: list[int]) -> str:
    def esc(cp: int) -> str:
        return "\\u{%X}" % cp

    return "".join(esc(a) if a == b else "%s-%s" % (esc(a), esc(b)) for a, b in ranges_of(cps))


sym_font = make_subset(dejavu, symbols, "Doc Converter Symbols")
emo_font = make_subset(noto, emoji, "Doc Converter Emoji")

# Everything some bundled font can draw (for the "can't render" warning).
supported = ranges_of(list(roboto | symbol_set | set(emoji) | {0x20, 0xA0, 0x200B, 0x200D, 0xFE0E, 0xFE0F, 0x20E3}
                           | set(range(0x1F3FB, 0x1F400))))
flat = [n for r in supported for n in r]

out = root / "src" / "convert" / "pdfFonts.generated.ts"
out.write_text(
    "// Generated by scripts/make-pdf-fonts.py — do not edit.\n"
    "// Fallback fonts for glyphs pdfmake's Roboto lacks; see THIRD_PARTY_NOTICES.md.\n"
    f'export const SYMBOL_FONT_BASE64 = "{base64.b64encode(sym_font).decode()}";\n'
    f'export const EMOJI_FONT_BASE64 = "{base64.b64encode(emo_font).decode()}";\n'
    f"export const SYMBOL_CHARS = /[{js_class(symbols)}]/u;\n"
    f"export const EMOJI_CHARS = /[{js_class(emoji)}]/u;\n"
    "// Flat [lo, hi, lo, hi, ...] code point ranges some bundled font can draw.\n"
    f"export const SUPPORTED_RANGES: number[] = {json.dumps(flat)};\n",
    encoding="utf-8",
)
print(
    f"symbols: {len(symbols)} glyphs / {len(sym_font)} B;  emoji: {len(emoji)} glyphs / {len(emo_font)} B;"
    f"  -> {out} ({out.stat().st_size // 1024} KB)"
)
